### PR TITLE
update main.tf with errorneous config

### PR DESCRIPTION
**Pull request by test-user-acct1**

### CODE REVIEW

**Comment by test-user-acct1** [comment]
atlantis apply

**Comment by test-user-acct1** [comment]
Oh no you got me there!

**Comment by test-user-acct1** [comment]
atlantis apply

**Comment by test-user-acct1** [comment]
YES!

**Comment by hazmei** [comment]
ok so atlantis can't merge the branch with commit signature verification enabled? Shall disable this for now

**Pull request merged**
