### PR TITLE
Update/secure

### PR DESCRIPTION
**Pull request by hazmei**
test for mergeability and faulty main.tf

### CODE REVIEW

**Comment by test-user-acct1** [comment]
atlantis plan

**Comment by test-user-acct1** [comment]
atlantis apply

**Comment by test-user-acct1** [comment]
1. so i'm unable to merge the pull request as i don't have the authorization being under dev group
2. atlantis doesn't lock state file if there's error in terraform plan
3. even if i add myself to  the reviewer, i'm still not authorized to merge it

**Note**: atlantis user needs to be part of the list (Restrict who can push to this branch requirement) in order to consider a pull request mergeable. Refer [here](https://www.runatlantis.io/docs/apply-requirements.html#supported-requirements)

**Comment by hazmei** [comment]
atlantis plan

**Comment by hazmei** [comment]
ok now that terraform plan does not throw any error, atlantis locks the state file

**Comment by test-user-acct1** [comment]
atlantis plan

**Comment by hazmei** [comment]
Can't approve this so i'm going to merge it anyway and do another testing with @test-user-acct1 PR

**Comment by test-user-acct1** [comment]
atlantis apply

**Comment by test-user-acct1** [comment]
ok so apparently the dev can apply :/ 👎  
is there a way we can prevent this?

**Pull request merged**
