### PR TITLE
good commit test

### PR DESCRIPTION
**Pull request by test-user-acct1**

### CODE REVIEW

**Comment by test-user-acct1** [comment]
ok so merging is blocked until at least 1 approving review

**Comment by hazmei** [comment]
"[Once apply requirement is satisfied, **ANYONE** that can comment on pull request can run the actual atlantis apply command.](https://www.runatlantis.io/docs/apply-requirements.html#setting-apply-requirements)" OH NO! What if the config from this PR is actually way behind compared to master? Read [here](https://www.runatlantis.io/docs/checkout-strategy.html#branch)

**Comment by hazmei** [comment]
Probably would be good if only the reviewer or admin could be the only one that can perform the apply command 👎

**Comment by test-user-acct1** [comment]
I can't merge this PR but i can apply the terraform changes

**Comment by test-user-acct1** [comment]
atlantis apply

**Comment by hazmei** [comment]
So once the plan looks good and PR is merged, atlantis release the lock for terraform state file

**Pull request merged**
